# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twittur', '0010_auto_20150522_1410'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorite',
            old_name='favorite_from',
            new_name='fromUser',
        ),
        migrations.RenameField(
            model_name='favorite',
            old_name='favorite_to',
            new_name='toUser',
        ),
        migrations.RenameField(
            model_name='group',
            old_name='group_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='group',
            old_name='group_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='group',
            old_name='group_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='group',
            old_name='group_picture',
            new_name='picture',
        ),
        migrations.RenameField(
            model_name='group',
            old_name='group_super',
            new_name='superGroup',
        ),
        migrations.RenameField(
            model_name='has',
            old_name='has_hashtag',
            new_name='hashtag',
        ),
        migrations.RenameField(
            model_name='has',
            old_name='has_message',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='hashtag',
            old_name='hashtag_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='isingroup',
            old_name='isInGroup_group',
            new_name='group',
        ),
        migrations.RenameField(
            model_name='isingroup',
            old_name='isInGroup_user',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='message_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='message_picture',
            new_name='picture',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='message_text',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='message_from',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='togroup',
            old_name='toGroup_group',
            new_name='group',
        ),
        migrations.RenameField(
            model_name='togroup',
            old_name='toGroup_message',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='togroup',
            old_name='toGroup_user',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='touser',
            old_name='toUser_from',
            new_name='fromUser',
        ),
        migrations.RenameField(
            model_name='touser',
            old_name='toUser_message',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='touser',
            old_name='toUser_to',
            new_name='toUser',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_academicDiscipline',
            new_name='academicDiscipline',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_lastSeen',
            new_name='lastSeen',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_nickname',
            new_name='nickname',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_password',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_picture',
            new_name='picture',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_studentNumber',
            new_name='studentNumber',
        ),
    ]
